### ISSUE TITLE
Multiprocessing Error

### ISSUE THREAD

**Issue by astromark** [dfm/emcee#166]
Hi,

I'm having an issue getting multiprocessing to work. I include the full error message below. Basically it's telling me that the function cannot be pickled. I thought it was a problem with the function at first but I get the same error message even if I just adapt the simple examples from the webpage to have threads >1. As you will notice, I'm running this in casa. I suspect this is the problem. Has anyone tried to run multiprocessing in casa before?

```python
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/mboot/alma/casa-release-4.4.0-el6/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/home/mboot/alma/casa-release-4.4.0-el6/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/mboot/alma/casa-release-4.4.0-el6/lib/python2.7/multiprocessing/pool.py", line 342, in _handle_tasks
    put(task)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed




^C
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)

/home/mboot/alma/casa-release-4.4.0-el6/lib/python2.7/casapy.py in <module>()
----> 1 
      2 
      3 
      4 
      5 

/home/mboot/.local/lib/python2.7/site-packages/emcee/sampler.pyc in run_mcmc(self, pos0, N, rstate0, lnprob0, **kwargs)
    155         """
    156         for results in self.sample(pos0, lnprob0, rstate0, iterations=N,
--> 157                                    **kwargs):
    158             pass
    159         return results

/home/mboot/.local/lib/python2.7/site-packages/emcee/ensemble.pyc in sample(self, p0, lnprob0, rstate0, blobs0, iterations, thin, storechain, mh_proposal)
    196         blobs = blobs0
    197         if lnprob is None:
--> 198             lnprob, blobs = self._get_lnprob(p)
    199 
    200         # Check to make sure that the probability function didn't return


/home/mboot/.local/lib/python2.7/site-packages/emcee/ensemble.pyc in _get_lnprob(self, pos)
    380 
    381         # Run the log-probability calculations (optionally in parallel).

--> 382         results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
    383 
    384         try:

/home/mboot/.local/lib/python2.7/site-packages/emcee/interruptible_pool.pyc in map(self, func, iterable, chunksize)
     96                 pass
     97             except KeyboardInterrupt:
---> 98                 self.terminate()
     99                 self.join()
    100                 raise

/home/mboot/alma/casa-release-4.4.0-el6/lib/python2.7/multiprocessing/pool.pyc in terminate(self)
    450         self._state = TERMINATE
    451         self._worker_handler._state = TERMINATE
--> 452         self._terminate()
    453 
    454     def join(self):

/home/mboot/alma/casa-release-4.4.0-el6/lib/python2.7/multiprocessing/util.pyc in __call__(self, wr)
    199             sub_debug('finalizer calling %s with args %s and kwargs %s',
    200                      self._callback, self._args, self._kwargs)
--> 201             res = self._callback(*self._args, **self._kwargs)
    202             self._weakref = self._callback = self._args = \
    203                             self._kwargs = self._key = None

/home/mboot/alma/casa-release-4.4.0-el6/lib/python2.7/multiprocessing/pool.pyc in _terminate_pool(cls, taskqueue, inqueue, outqueue, pool, worker_handler, task_handler, result_handler, cache)
    480 
    481         debug('helping task handler/workers to finish')
--> 482         cls._help_stuff_finish(inqueue, task_handler, len(pool))
    483 
    484         assert result_handler.is_alive() or len(cache) == 0

/home/mboot/alma/casa-release-4.4.0-el6/lib/python2.7/multiprocessing/pool.pyc in _help_stuff_finish(inqueue, task_handler, size)
    465         # task_handler may be blocked trying to put items on inqueue

    466         debug('removing tasks from inqueue until task handler finished')
--> 467         inqueue._rlock.acquire()
    468         while task_handler.is_alive() and inqueue._reader.poll():
    469             inqueue._reader.recv()
```

**Comment by dfm** [comment]
I'm not familiar with "casa" so I might not be the best person to answer but two things to try:

1. Can you try pickling your function and see if that works? Just so that we can track down the real issue. `import pickle; pickle.dumps(function)`

2. How are you executing your script? Do you run `python script.py` or are you running it interactively. This can make functions non-picklable.

**Comment by astromark** [comment]
Hi, thanks for the tips. I am running the script interactively. The casa helpdesk have finally gotten back to me to let me know that it is not possible to run casa without ipython, so I think I shall have to look for a way to compute my likelihood without casa.
