### ISSUE TITLE
Unpickling error when using emcee over multiple nodes

### ISSUE THREAD

**Issue by guillochon** [dfm/emcee#200]
I have been able to get my code that's wrapping emcee functional via MPI, but it appears to only work when the job is running on a single node with multiple CPUs (e.g. my laptop, single node on a cluster). When I attempt to run on multiple nodes, I get an unpickling error:

``` bash
Traceback (most recent call last):
  File "/n/home01/jguilloc/envs/PY34/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/n/home01/jguilloc/envs/PY34/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/n/home01/jguilloc/envs/PY34/lib/python3.4/site-packages/mosfit-0.1.5-py3.4.egg/mosfit/__main__.py", line 6, in <module>
    main.main()
  File "/n/home01/jguilloc/envs/PY34/lib/python3.4/site-packages/mosfit-0.1.5-py3.4.egg/mosfit/main.py", line 269, in main
    pool.wait()
  File "/n/home01/jguilloc/envs/PY34/lib/python3.4/site-packages/emcee-2.2.1-py3.4.egg/emcee/mpi_pool.py", line 94, in wait
  File "MPI/Comm.pyx", line 1192, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:106889)
  File "MPI/msgpickle.pxi", line 292, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:43053)
  File "MPI/msgpickle.pxi", line 143, in mpi4py.MPI.Pickle.load (src/mpi4py.MPI.c:41248)
_pickle.UnpicklingError: invalid load key, '^H'.
```

The code that is invoking emcee is here, I've highlighted the line with the emcee call: https://github.com/guillochon/MOSFiT/blob/master/mosfit/fitter.py#L281-L282.

Part of the trickery to get the current implementation working was to make the model object, which is initialized independently on all nodes, global. I imagine this could be a source of the error, but I'm not sure how to get it working without the global approach.

**Comment by dfm** [comment]
It's hard to debug something like this and I unfortunately don't have a solution off the top of my head. Can you try to build the minimal demo that crashes the same way?

**Comment by guillochon** [comment]
@dfm I'll try, but my worry here is that the bug is related to the `global` object particulars. It's also not behaving the same way on another cluster I'm trying this on; instead of throwing an `UnpicklingError` it simply stalls forever.

I do see with some Googling that there are other circumstances in which `UnpicklingError`s were see when too many walkers were being used, both in emcee and also in Ben Farr's kombine: https://github.com/bfarr/kombine/issues/11

The nature of this suggests to me that the pickles are being encoded incorrectly by mpi4py, as perhaps python2 strings rather than python3. But I am not sure.

**Comment by manodeep** [comment]
So is there any way to try with fewer walkers? And I second @dfm -- hard to debug without a minimal failing demo. 

I have also seen weird MPI errors with large number of walkers and those errors got resolved by simply using `mpi4py/bin/python-mpi` instead of `python`.

**Comment by guillochon** [comment]
@pkgw had helped track this bug down for me a while ago, it was related to how my pool was being initialized. Closing.
