### ISSUE TITLE
Error when using MPI

### ISSUE THREAD

**Issue by sshres** [dfm/emcee#244]
I'm only seeing this error at the end when using MPIPool in the emcee sampler, it works fine with a multiprocessing pool.

```
> Traceback (most recent call last):
>   File "mpiemcee.py", line 121, in <module>
>     pos, prob, state = sampler.run_mcmc(p0, 10)
>   File "/home/sash7676/anaconda2/lib/python2.7/site-packages/emcee/sampler.py", line 172, in run_mcmc
>     **kwargs):
>   File "/home/sash7676/anaconda2/lib/python2.7/site-packages/emcee/ensemble.py", line 198, in sample
>     lnprob, blobs = self._get_lnprob(p)
>   File "/home/sash7676/anaconda2/lib/python2.7/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
>     results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
> TypeError: 'NoneType' object is not iterable
```
Has anybody had this problem?

**Comment by dfm** [comment]
What version of emcee are you using? How did you install it? Please make a minimal working example that demonstrates this issue.

**Comment by sshres** [comment]
I used 'pip install emcee' today. The code worked fine when I used the ProcessingPool from pathos.multiprocessing but since I wanted to run my code on a cluster, I thought I'd use MPI which when I get the above posted error.
Here's the full code: https://github.com/sshres/CoupledModel/blob/master/mpiemcee_coupled.py
since the log posterior was a bit complicated to post here.

**Comment by dfm** [comment]
Can you please write the minimal working code snippet? It shouldn't depend
on your data or your specific model. That way we can nail down where the
issue is coming from. You should also say exactly what command line
argument you're executing to run your script with MPI.

Also: what does emcee.__version__ say? And how did you install mpi4py? What
version of mpi4py is it?

**Comment by dfm** [comment]
Also: you might want to double check the emcee MPI docs:
http://emcee.readthedocs.io/en/stable/user/advanced.html#using-mpi-to-distribute-the-computations
