### ISSUE TITLE
Test  test_nan_lnprob failing 

### ISSUE THREAD

**Issue by sergiopasra** [dfm/emcee#293]
**General information:**

- emcee version: 2.2.1
- platform: x86_64
- installation method (pip/conda/source/other?): source

**Problem description:**
I'm building emcee with **python 3.7** and **numpy 1.16.1** in the Fedora build system

https://koji.fedoraproject.org/koji/taskinfo?taskID=32454853

### Expected behavior:
The tests run OK after installation

### Actual behavior:

ERROR: emcee.tests.Tests.test_nan_lnprob

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILDROOT/python-emcee-2.2.1-12.fc30.x86_64/usr/lib/python3.7/site-packages/emcee/tests.py", line 184, in test_nan_lnprob
    self.check_sampler(p0=p0)
  File "/builddir/build/BUILDROOT/python-emcee-2.2.1-12.fc30.x86_64/usr/lib/python3.7/site-packages/emcee/tests.py", line 112, in check_sampler
    for i in self.sampler.sample(p0, iterations=N):
  File "/builddir/build/BUILDROOT/python-emcee-2.2.1-12.fc30.x86_64/usr/lib/python3.7/site-packages/emcee/ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "/builddir/build/BUILDROOT/python-emcee-2.2.1-12.fc30.x86_64/usr/lib/python3.7/site-packages/emcee/ensemble.py", line 364, in _get_lnprob
    if np.any(np.isinf(p)):
TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by sergiopasra** [comment]
This is fixed in the latest version (3.0.0)
