### ISSUE TITLE
Backend in parallel ValueError: Zero-sized dimension specified (zero-sized dimension specified)

### ISSUE THREAD

**Issue by AdamJMcMullen** [dfm/emcee#384]
**General information:**
- python version: 3.8.2
- emcee version: 3.02
- h5py version: 3.1.0
- platform: linux
- installation method (pip/conda/source/other?): pip

**Problem description:**

### Expected behavior: 
On a single process in MPI save chain to h5 file with backends

### Actual behavior: ValueError: 
Zero-sized dimension specified (zero-sized dimension specified)
Traceback (most recent call last):
  File "./test.py", line 184, in <module>
    state=sampler.run_mcmc(pos, 100, progress=True);
  File "/global/home/hpc4783/.local/lib/python3.8/site-packages/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/global/home/hpc4783/.local/lib/python3.8/site-packages/emcee/ensemble.py", line 322, in sample
    self.backend.grow(iterations, state.blobs)
  File "/global/home/hpc4783/.local/lib/python3.8/site-packages/emcee/backends/hdf.py", line 185, in grow
    g.create_dataset(
  File "/global/home/hpc4783/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 148, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/global/home/hpc4783/.local/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 89, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1629, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1653, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1685, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1477, in h5py.h5t._c_array
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5t.pyx", line 330, in h5py.h5t.array_create
ValueError: Zero-sized dimension specified (zero-sized dimension specified)

### What have you tried so far?: 
I tried setting blobs to None. I can run emcee in serial fine with the likelihood.

### Minimal example:

My problems lies here:

"Certain operations in HDF5, for example, anything which modifies the file metadata, must be performed by all processes. Other operations, for example, writing data to a dataset, can be performed by some processes and not others"

I think it could be solved by opening the file with swmr 

Some pseudo code
```python
import emcee
import h5py
from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
nprocs = comm.Get_size()

# sample code goes here...

#load data from h5 file
with h5py.File('kdes.h5', 'r') as hf:
    for i in range(rank,len(random_data_ind),nprocs):
        nearest_muon_energy.append(hf['nearest_muon_energy'][num_muon_energy[i]:num_muon_energy[i+1]])

#not necessary to close
hf.close()


def loglikelihood(theta,stopp):
    stopp[0]=comm.bcast(stopp[0],root=0)
    theta=comm.bcast(theta,root=0)
    likelihood=-np.inf
    if stopp[0]==0:
        compute num_expected across multiple processes using MPI operations, this involves loading some monte carlo data from a file 'montecarlodata.h5'

        num_expected=do some math on the data from nearest_muon_energy

        likelihood=-num_expected+num_observed*np.log(num_expected)-log_factorial

        combine results from each process to return

        if not np.isfinite(likelihood):
            return -np.inf
    return likelihood

def log_prior(theta):
    gamma,phi_astro,phi_atm,phi_muon,dgamma,g,mx,mphi = theta
    uniform prior

def log_probability(theta,stopp):
    if rank ==0:
        lp  = log_prior(theta)
        if not np.isfinite(lp):
            return -np.inf
        return lp + loglikelihood(theta,stopp)
    else:
        loglikelihood(theta,stopp)


if rank == 0:
    stop=[0]
    pos = np.array([-2.0, 2.1464,1.08,0.8851,0.0,0.01,1e8,1e6]) + 1e-1*np.random.randn(24,8) * np.array([-2.0, 2.1464,1.08,0.8851,0.01,0.01,1e8,1e6])
    nwalkers, ndim = pos.shape

    backend = emcee.backends.HDFBackend("DM_emcee_kde.h5")
    backend.reset(nwalkers,ndim)
    sampler = emcee.EnsembleSampler(nwalkers, ndim, log_probability,args=[stop],backend=backend)
    print(sampler)

else:
    stop=[0]
    state=np.zeros(8)
    while stop[0]==0:
        log_probability(state,stop)

```

**Comment by dfm** [comment]
Is there a reason why you're reimplementing MPI support instead of using the supported method: https://emcee.readthedocs.io/en/stable/tutorials/parallel/#mpi

**Comment by AdamJMcMullen** [comment]
> Is there a reason why you're reimplementing MPI support instead of using the supported method: https://emcee.readthedocs.io/en/stable/tutorials/parallel/#mpi

Yes my likelihood function contains for loops that are coded to run in parallel. I am new to mpi, and don't know how the built in methods work, but I assumed they worked by distributing the work across walkers.

**Comment by dfm** [comment]
OK - Can you put together a simpler version of this code that executes (i.e. is actually fully implemented and doesn't require a data file) and gives the same error? I'm happy to take a look at debugging that.

**Comment by AdamJMcMullen** [comment]
For sake of time I just decided to write to my own h5 file to save the chain every n steps
